apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
      version: "2.5.8"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: pihole
