apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: pihole
      version: "2.5.8"
  interval: 1h0m0s
  values:
    image:
      repository: "pihole/pihole"
      tag: "2022.04.1"
      pullPolicy: IfNotPresent

    serviceDns:
      mixedService: false
      type: LoadBalancer
      port: 53
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.0.53
        metallb.universe.tf/allow-shared-ip: pihole-dns-tcp,pihole-dns-udp

    serviceDhcp:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.0.67

    admin:
      existingSecret: "pihole"
      passwordKey: "password"

    dnsmasq:
      customDnsEntries:
        - address=/k8s-master/192.168.0.100
        - address=/k8s-worker0/192.168.0.101
        - address=/k8s-worker1/192.168.0.102
        - address=/k8s-worker2/192.168.0.103
        - address=/nas/192.168.0.120

    monitoring:
      podMonitor:
        enabled: true
        interval: 30s
        labels:
          release: kube-prometheus-stack
      sidecar:
        enabled: true
        port: 9617
        image:
          repository: ekofr/pihole-exporter
          tag: v0.3.0
          pullPolicy: IfNotPresent
