apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns
resources:
  - sealedsecret.yaml
  - helmrepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: pihole
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
