apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns
  namespace: duckdns
spec:
  encryptedData:
    TOKEN: AgCr0DS4sH+Y8Pel6tKbr64axzVpPEQzXsuLZt3WQ1TUeA7bJGAY8Q0+iW2IZ/29wW1jROQNTcEkEEVw6RKjjIbkP8mCEhPfbAQ/kj4Y/ip/6ea8a/GWdzsfBPPm0U9EwzEiF/o1P7gcfcsxbdyXSx7LaFDvTZJjLQ82o1LHbwGPhhOdRwDnn5d7Tvh6D5LklZ+lQPolN65pXao+1sLF6w4Z9w2/e1usIcS5eWVocp+o77HCKpEDQVezFnSV9lrflSNEYVvYGjwf7K/ZCbSRVnAaL6F8I2Mlz0/ODS/ysc3iFvwpzsdPhZTQIIbiR7PO8C7s14NI110ceY4srLjKl7caBIbVuTPx4gZIcLV8ao7jxLTi2iwOEj7+UvYiE3+4Kj2fg7fHBww3r7m9qSCIw/mhyIe0v+eMjVgD12lKC1/GEJ3tK9rmtntGD0QisM0Ag/sUf59ZZye1YdXv5+PEm49tF5ODn1qYi/1tzUfFsax58iUvD3CMlKDP1NvqaHcP/9X2iGlalQWL+hOiiv038Np8SIy033dJkaKKE5Ti4KN/8Q0HyWqS9WgqIbAyBiSuWJtEDDWkD31PH5DYJZqbi7usmIgQ64rbyOu5RjDJT5WCqE+h1XKCiuNLosxflh2PQmwsLzgrX3lOL/Fx5W2ikwL3VmlulMaOymXgqQHyCUAr3/5x149lT6HizTToJ2fCV3e6XcTYACZmeM3c2hSNQ9W6vzFA6zPJbWzJYpKkoorm8t+lUqo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: duckdns
      namespace: duckdns

